# site
url: "https://madeindra.github.io"
title: "Made Indra"
permalink: "/:title/"

# header
home_enabled: true
about_enabled: true
contact_enabled: true

# footer
sitemap_enabled: true

# homepage
homepage:
  welcome:
    title: "Welcome to My Blog"
    subtitle: "Here, I share insights on technology, travel, and health. Join me as we explore fascinating topics and uncover new perspectives."

# plugins
plugins:
  - jekyll-postcss
  - jekyll-feed

# jekyll-postcss
postcss:
  cache: false

# exclude from build
exclude:
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js

