# site
url: "https://madeindra.dev"
title: "madeindra.dev"
author: "Made Indra"
permalink: "/:title/"
description: "A blog by Made Indra sharing insights, tutorials, and stories about software development, technology trends, personal passions, plus a bit of everything else!"
keywords: 
  - blog

# header
logo_image: "/assets/images/logo.webp"
search_enabled: true
home_enabled: true
about_enabled: true

# footer
sitemap_enabled: true
feed_enabled: true

# homepage
homepage:
  welcome:
    title: ""
    subtitle: ""

# about
about:
  author_name: "Made Indra"
  author_image: "/assets/images/author.webp"
  social_media_enabled: true
  description:
    - "Hey there!"
    - "I'm Made Indra, a software engineer with years of experience in various industries. My expertise is in backend engineering, and I'm currently expanding into frontend development. What I love most about being a software engineer is constantly learning new technologies, meeting diverse people, and gaining new perspectives. These are the highlights of my journey."
    - "When I'm not coding, I enjoy reading fiction, playing games, and capturing the beauty of the world through photography. My greatest passion is sharing my knowledge. In my free time, I volunteer as a mentor and create content for social media, spreading the magic of software engineering to everyone who shares this curiosity."

# social media
social_media:
  email: ""
  linkedin: "indramade"
  github: "madeindra"
  youtube: ""
  bsky: ""
  twitter: ""
  instagram: ""

# plugins
plugins:
  - jekyll-postcss
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# jekyll-postcss
postcss:
  cache: false

# jekyll-paginate
paginate: 10
paginate_path: '/page/:num/'

# exclude from build
exclude:
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js

# highlighted link
highlights:
  - "/banyak-jalan-menuju-jerman"
  - "/perlukah-ikut-bootcamp"
  - "/bingung-memilih-jurusan"
  - "/lanjut-kuliah-atau-kerja"

